variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - lint
  - build

services:
  - docker:dind

pylint:
  image: python:latest
  stage: lint
  script:
    - curl -o .pylintrc https://tool.ix.ai/.pylintrc
    - pip install flask pylint python-telegram-bot waitress
    - pylint --rcfile=.pylintrc src/*.py

build:docker:
  image: docker:latest
  stage: build
  only:
    - /^latest$/
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
